### ISSUE TITLE
Cooming -> Coming

### ISSUE THREAD

**Issue by yeskunall** [chernivtsijs/chernivtsijs.github.io#9]
I _think_ [this](https://github.com/chernivtsijs/chernivtsijs.github.io/blob/premaster/index.pug#L33) might be a typo? I'm not sure. If it is, I'd be glad to make a PR to fix this. If not, please feel free to close this.

Great website, BTW. 💯

**Comment by denysdovhan** [comment]
Good catch! Please, fix 🙏🏻

**Comment by yeskunall** [comment]
Done! #10.
